In [35]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__


'3.0.6'

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")


In [9]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2


In [13]:
# 1. Get the total number of rows (fastest & most common)
total_rows = len(df)

total_rows


10000

In [16]:
df.fuel_type.nunique()

3

In [18]:
df.fuel_efficiency_mpg.max()


np.float64(41.2)

In [19]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [21]:
df.horsepower.median()

np.float64(254.0)

In [22]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [23]:
# Find the most frequent value (the [0] grabs the top value in case of a tie)
most_frequent_value = df['horsepower'].mode()[0]

# Replace the missing (NaN) values in that column
df['horsepower'] = df['horsepower'].fillna(most_frequent_value)

df['horsepower'] 

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...  
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [24]:
df.horsepower.isnull().sum()

np.int64(0)

In [25]:
df.horsepower.median()

np.float64(252.0)

In [26]:
asia_cars = df[df['origin'] == 'Asia']

In [27]:
selected_columns = asia_cars[['vehicle_weight', 'model_year']]

In [28]:
first_7 = selected_columns.head(7)

In [30]:
X = first_7.values

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [32]:
XTX = X.T.dot(X) 
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [37]:
XTX_inv = np.linalg.inv(XTX)

XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [38]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [39]:
w = XTX_inv.dot(X.T).dot(y) 

In [40]:
final_sum = w.sum()
print("The sum of all elements is:", final_sum)

The sum of all elements is: 0.36919696904925486
